### ISSUE TITLE
Optional quests objectives

### ISSUE THREAD

**Issue by BananaFlambe** [SpartanVXL/DDO-Translation#28]
I can't find the files that contain the objectives of the optional quests. Tried searching the text but didn't find any file, example: Goblin Slinger (Lvl 1~)を討伐 , I tried searching for "を討伐" and didn't find anything.

**Comment by Crevox** [comment]
I already translated it, it's just not in the current patch. :)

**Comment by weisspe** [comment]
How do we convert the .xml files into the .arc files included in the
patch?  We've made a lot of progress that I kind of want to have while
playing.  I'm also concerned I might have caused issues with formatting on
a few and want to test them and make any formatting tweaks I need to before
the next patch for the public.

**Comment by Crevox** [comment]
Only Riftcrystal has access to the tools to do that.

I stand in the same situation, but for now, it's what we have.

**Comment by weisspe** [comment]
@riftcrystal can you share how this is done?  I'm a software dev in my day job so I'm comfortable getting a tool chain and learning something if I need to.

If the how needs to stay secretive for whatever reason that's fine, but can we put in a request to package up a version soon? :)
