### ISSUE TITLE
Clarification on six (or more) priest skills.

### ISSUE THREAD

**Issue by Iztooi** [SpartanVXL/DDO-Translation#33]
I noticed that in the last modification in the skills names file all of the skills (but 5) have been translated.
The skills i would like a clarification on are the ones who reduces the elemental damage taken or reduce the chance of being affected by the elemental status (burn/frozen/paralyzed).
The skills that reduce the damage taken by the element have been called "anti-element" while the skills that reduce the chance of the effect have been called "reduce element". Shouldn't it be the other way around? Since (e.g.) reduce fire recalls the fire damage reduction, while anti-fire recalls the fire status prevention (like something flameproof).
These considerations are just for translation refining/localization.

**Comment by Crevox** [comment]
The names were coming from the public spreadsheet and are definitely open to critique and refinement.

I'll take a second look later today, and I'm open to any suggestions.
