### ISSUE TITLE
Ability Clarifications

### ISSUE THREAD

**Issue by Crevox** [SpartanVXL/DDO-Translation#34]
Please take some time to read over the passive descriptions I committed in ability_info.xml to ensure they are correct.

There are a couple (Shield Sage ones) that I was just not confident on at all to create a description for. This also does not cover Secret Abilities yet.

**Comment by BananaFlambe** [comment]
Just read them, and as a shield sage player I can tell you that those are well translated, like the others :+1:

**Comment by Crevox** [comment]
I'm talking about the untranslated ones. ;p

Ability 86 and 89:

盾ガード時や武器ヒット時によろめいた際に
受けるダメージ量が軽減される

ガード不能攻撃を防御した際の
ダメージが軽減される

Also, Seeker ability 109:

揺さぶりによるスタミナ消費量が軽減される

I'm not certain on what these do.

**Comment by BananaFlambe** [comment]
The first one is like "Damage received during guard break is reduced" that's when you receive a heavy blow and in that timeframe someone attacks you.

The second one is "Damage received while being staggered from overblocking is reduced" this one refers to the blocking power of the shield, if the power of the attack is above a certain amount you will get damaged anyways.

The seeker one reduces the stamina used for bringing down big enemies, when you click with the right mouse button.

**Comment by Crevox** [comment]
Thanks, I made the adjustments. :)
