### ISSUE TITLE
Dreed/Dread/Dorido

### ISSUE THREAD

**Issue by Crevox** [SpartanVXL/DDO-Translation#35]
Which one?

ドリード Castle

Dreed/Dread/Dorido

**Comment by BananaFlambe** [comment]
The ー after "リ/Ri" is used to extend the pronunciation of the previous katakana, in this case "リー" is Rii, knowing this I would go for Dreed or Dread, IMO I prefer Dread because it makes more sense.

**Comment by weisspe** [comment]
I vote for Dreed because I think there's already dread somewhere else that wasn't spelled that way originally.  They're probably different for a reason (I'm just not sure what dreed is).
