### ISSUE TITLE
q60000008_00.xml Sorcerer tutorial issue

### ISSUE THREAD

**Issue by BananaFlambe** [SpartanVXL/DDO-Translation#39]
There are issues with the sorcerer tutorial quest objectives, the first step doesn't exist (Talk to the white knight near the cliff) because of this all of the other objectives are one step behind the quest, there is also another objective missing, the one that requires you to press c to change spell distance.

Refer to this post to help you fixing this: https://www.reddit.com/r/dragonsdogmaonline/comments/3jpw5c/sorcerer_basics_tutorial_quest/

**Comment by Crevox** [comment]
This should be fixed now, sorry about that.

**Comment by BananaFlambe** [comment]
Thanks :)
