### ISSUE TITLE
Question for Quest Files

### ISSUE THREAD

**Issue by MasterCyria** [SpartanVXL/DDO-Translation#51]
In the quest files, a few lines seem to have formatting like this in the Japanese language portion: 

 <original xml:space="preserve">敵には&lt;COL ff7575&gt;&lt;PADM&gt;&lt;KEYN RL&gt;／&lt;KEYN RU&gt;&lt;KEYM&gt;左／右クリック&lt;/KEYM&gt;&lt;/COL&gt;で基本攻撃！</original>

Should we remove the non-Japanese characters, or with this intentional? 

Example: DDO-Translation/ui/00_message/quest/q00000001.xml

**Comment by Crevox** [comment]
Those are likely controller/keyboard buttons in the text (like images).

**Comment by MasterCyria** [comment]
Sure enough. That 2nd phrase is "Left/Right Click". There isn't anyway for me to test an updated file in the game without Riftcrystal creating a new patch, is there? Just to make sure translating the text doesn't break the image files.

**Comment by Crevox** [comment]
No, sadly.
