### ISSUE TITLE
Question about Keys ID number order

### ISSUE THREAD

**Issue by Maerkaryz** [SpartanVXL/DDO-Translation#54]
Hello.
Nice to meet you
2 days ago I asked Spartan on Reddit if I can help to translate few things.
I created a fork with few commits already. 

I have a question please.

Can we change keys'ID number like:

original file:
ENEMY_NAME_1
ENEMY_NAME_2
ENEMY_NAME_3

or can it be
ENEMY_NAME_16
ENEMY_NAME_32
ENEMY_NAME_24

I mean can it be patched or need to respect original order?

Thank you.

**Comment by Crevox** [comment]
I'm not positive on your question. Can you clarify? Do you just want to change the order of the message keys in the file?

**Comment by Maerkaryz** [comment]
Hello Sir. Nice to meet you.
I wanted to know exactly how much language strings were translated or not and as I used few months ago a website to help developper to translate into several languages I gave it a try.

Black Desert Online used 
http://ospft47.oneskyapp.com/collaboration/project?id=48333
and here an example with DDO
https://osja6sh.oneskyapp.com/collaboration

Problems are that I can't use directly XML Format to do it (Or I failed to found a way to make it work) so I have to convert it into CSV Format.
key,original,translation,resource_Id
"ACHIEVEMENT_CATEGORY_1","冒険","Adventure",0
"ACHIEVEMENT_CATEGORY_2","戦闘","Combat",0
"ACHIEVEMENT_CATEGORY_3","成長","Growth",0

Importing that on the website you'll  get translated strings done.
But once we're done and want to export the order of the message keys could change.
Right now oneskyapp.com keep message keys orders.

But in cake it failed is it a big deal to keep original message key orders ?

Thanks.

**Comment by SpartanVXL** [comment]
The Key ID needs to be kept the same, It's what identifies the strings in the game for translation. The only things that should be added are the translation text.

**Comment by Maerkaryz** [comment]
I understood that Key ID must be the same. I'm talking about order.
Can it be

Item_12
Item_78
Item_89

Instead of  (original files)
Item_1
Item_2
Item_3

**Comment by SpartanVXL** [comment]
Oh the ordering of the keys...you would have to ask riftcrystal as he is the one who reads the files to make the patch.

I don't see why there would be a problem having them in a different order...but it would be good to just leave them ordered so the translations aren't jumbled around.

**Comment by riftcrystal** [comment]
Order does not need to be maintained except for files that either have no keys, or have duplicate keys (both of which do happen).
