### ISSUE TITLE
Warrior's Cling Attack - 魔倒斬り

### ISSUE THREAD

**Issue by Crevox** [SpartanVXL/DDO-Translation#58]
On the DDON skill translation document, someone translated Warrior's clinging attack, 魔倒斬り, as "Crush."  Based on what I can see from the kanji, this doesn't seem accurate.

Anyone have any ideas?

**Comment by xYuunaX** [comment]
Think someone fixed the translation on the spreadsheet.

Inverse Slash - While clinging to an enemy, the user readies the blade briefly, and delivers a single devastating blow.
